### ISSUE TITLE
Make title bar link targets different

### ISSUE THREAD

**Issue by vinzv** [Gravemind/tt-rss-feedlish-theme#2]
First of all: thank you so much for your efforts! It's a real relieve compared to the new stock theme!

One thing I miss from the earlier Feedly theme is the different behaviour for title bar links. With your theme clicking the title bar of an opened article opens the URL in a new window, disregarding where one clicks. In the former theme versions clicking the headline (red aread of screenshot) opened the article while clicking the bar (green area) collapsed the article.
Would it be possible to get this behaviour back?
![bildschirmfoto von 2018-12-17 16-59-01](https://user-images.githubusercontent.com/74432/50099211-dd342500-021d-11e9-9ffc-9f7f1d3bcbec.png)

**Comment by Gravemind** [comment]
Yes I agree. 

It's the same behavior as the default theme. I don't know if it's a new since 18.12, or if the old feedly theme found a way to do it in CSS only.

I couldn't find a way to do this properly, yet.

**Comment by Gravemind** [comment]
I committed something, the css is pretty hacky, but that's a first step.

In combined-auto-expand mode, I think I would prefer having left-click always doing collapse/expand, and middle-click/ctrl-click always opening the url... But that would require changing tt-rss javascript, and not sure everyone would agree...

**Comment by vinzv** [comment]
For me that's perfect and exactly what I needed as it's the same behaviour as before the apocalyptic changes in TTRSS. Thank you so much - you revived my reading workflow!
