### ISSUE TITLE
Feed name button not present when looking at specific feed

### ISSUE THREAD

**Issue by jamespo** [Gravemind/tt-rss-feedlish-theme#4]
If I look at a specific feed the button with the feed name for each article isn't there - there is a gap instead

![image](https://user-images.githubusercontent.com/1472544/50286554-a8131700-0457-11e9-9d4f-f76f04d5726e.png)

The button isn't there with the default theme either, but there's no gap

**Comment by Gravemind** [comment]
Yes, [I couldn't find a proper solution yet](https://github.com/Gravemind/tt-rss-feedlish-theme/blob/master/feedlish.less#L349).

I think it's a change after 18.8: now, tt-rss emits the emplacement for the feed name, but the name inside is empty. At 18.8, I think the [whole emplacement wasn't emitted at all](https://git.tt-rss.org/fox/tt-rss/src/18.8/classes/feeds.php#L552).

If I cannot find a solution, I might send a couple Issues or PRs to tt-rss...

**Comment by levito** [comment]
I kind of solved this by setting the width not on `.feed` but on the contained `.feed a` while also hiding `.feed a:empty`. See https://github.com/levito/tt-rss-feedly-theme/commit/a40709265593f3912381487375023ce9d290cb63.

The downside of this is that feed names don't shrink anymore if they are shorter. For me this was an acceptable compromise.

**Comment by Gravemind** [comment]
Thanks @levito ! For now, I personally prefer to keep the short feed title version.

I made a [PR to tt-rss](https://git.tt-rss.org/fox/tt-rss/pulls/102) with the most PR-worthy fix I found.

**Comment by Gravemind** [comment]
tt-rss has now a [neat `is-vfeed` attribute](https://git.tt-rss.org/fox/tt-rss/commit/8b26b8629f0c7c327cfbac76eb22f65341f31397) (Thanks [fox](https://git.tt-rss.org/fox) ) to deal with this issue in themes.

@levito: [here is](https://github.com/Gravemind/tt-rss-feedlish-theme/commit/e43dc686a5dbfd7179c5651128314f559f264a30) how I used it.

**Comment by levito** [comment]
Awesome, thanks! [I also use it now](https://github.com/levito/tt-rss-feedly-theme/commit/1289b6c5eb8885a67beb0876e7d43315e8e0145b)
